# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r: bioc-release

cache: packages
warnings_are_errors: false

env:
 global:
#   - _R_CHECK_FORCE_SUGGESTS_: false
   - _R_CHECK_LENGTH_1_CONDITION_: true
   - _R_CHECK_LENGTH_1_LOGIC2_: true

r_build_args: "--no-manual --no-resave-data"
r_check_args: "--no-build-vignettes --no-manual --timings"